name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag robot-container
    - name: Run Robot Framework tests
      run: docker run -it -v .\tests\:/tests robot-container robot --dry-run tests/test1.robot
